// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GroupsGet implements GET /groups operation.
//
// Get all groups.
//
// GET /groups
func (UnimplementedHandler) GroupsGet(ctx context.Context) (r []Group, _ error) {
	return r, ht.ErrNotImplemented
}

// GroupsIDDelete implements DELETE /groups/{id} operation.
//
// Delete group by id.
//
// DELETE /groups/{id}
func (UnimplementedHandler) GroupsIDDelete(ctx context.Context, params GroupsIDDeleteParams) (r GroupsIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GroupsIDGet implements GET /groups/{id} operation.
//
// Get group by id.
//
// GET /groups/{id}
func (UnimplementedHandler) GroupsIDGet(ctx context.Context, params GroupsIDGetParams) (r GroupsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GroupsIDPut implements PUT /groups/{id} operation.
//
// Update group by id.
//
// PUT /groups/{id}
func (UnimplementedHandler) GroupsIDPut(ctx context.Context, req *GroupUpdate, params GroupsIDPutParams) (r GroupsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GroupsPost implements POST /groups operation.
//
// Create group.
//
// POST /groups
func (UnimplementedHandler) GroupsPost(ctx context.Context, req *GroupUpdate) (r *Group, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthzGet implements GET /healthz operation.
//
// GET /healthz
func (UnimplementedHandler) HealthzGet(ctx context.Context) (r *Ok, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGet implements GET /users operation.
//
// Get all users.
//
// GET /users
func (UnimplementedHandler) UsersGet(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDDelete implements DELETE /users/{id} operation.
//
// Delete user by id.
//
// DELETE /users/{id}
func (UnimplementedHandler) UsersIDDelete(ctx context.Context, params UsersIDDeleteParams) (r UsersIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDGet implements GET /users/{id} operation.
//
// Get user by id.
//
// GET /users/{id}
func (UnimplementedHandler) UsersIDGet(ctx context.Context, params UsersIDGetParams) (r UsersIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDGroupPut implements PUT /users/{id}/group operation.
//
// Update user group by id.
//
// PUT /users/{id}/group
func (UnimplementedHandler) UsersIDGroupPut(ctx context.Context, req *UsersIDGroupPutReq, params UsersIDGroupPutParams) (r UsersIDGroupPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDPut implements PUT /users/{id} operation.
//
// Update user by id.
//
// PUT /users/{id}
func (UnimplementedHandler) UsersIDPut(ctx context.Context, req *UserUpdate, params UsersIDPutParams) (r UsersIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// Create user.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context, req *UserUpdate) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
