// Code generated by ogen, DO NOT EDIT.
package openapi

type GroupsIDDeleteRes interface {
	groupsIDDeleteRes()
}

type GroupsIDGetRes interface {
	groupsIDGetRes()
}

type GroupsIDPutRes interface {
	groupsIDPutRes()
}

type UsersIDDeleteRes interface {
	usersIDDeleteRes()
}

type UsersIDGetRes interface {
	usersIDGetRes()
}

type UsersIDGroupPutRes interface {
	usersIDGroupPutRes()
}

type UsersIDPutRes interface {
	usersIDPutRes()
}
